## Gradient Descent

In [1]:
import torch
import torch.nn.functional as F
# 이 실습에서는 low level로 해보기. 

In [2]:
target = torch.FloatTensor([[.1, .2, .3],
                           [.4, .5, .6],
                           [.7, .8, .9]])

In [3]:
x = torch.rand_like(target)
# This means the final scalar will be differentiate by x.
x.requires_grad = True
# You can get gradient of x, after differentiation.

x

tensor([[0.9960, 0.1936, 0.8734],
        [0.9084, 0.6689, 0.4719],
        [0.3829, 0.4554, 0.2604]], requires_grad=True)

In [4]:
loss = F.mse_loss(x, target)

loss

tensor(0.2293, grad_fn=<MseLossBackward0>)

In [5]:
threshold = 1e-5
learning_rate = 1.
iter_cnt = 0

while loss > threshold:
    iter_cnt += 1
    loss.backward() # Calculate gradients.
    
    x = x - learning_rate * x.grad
    
    # You don't need to aware this now.
    x.detach_() # 그래프를 끊어줌. . .
    x.requires_grad_(True)
    
    loss = F.mse_loss(x, target)
    
    print('%d-th Loss: %.4e' % (iter_cnt, loss))
    print(x)

1-th Loss: 1.3869e-01
tensor([[0.7969, 0.1950, 0.7460],
        [0.7954, 0.6314, 0.5003],
        [0.4534, 0.5320, 0.4025]], requires_grad=True)
2-th Loss: 8.3900e-02
tensor([[0.6420, 0.1961, 0.6469],
        [0.7075, 0.6022, 0.5225],
        [0.5082, 0.5915, 0.5131]], requires_grad=True)
3-th Loss: 5.0754e-02
tensor([[0.5216, 0.1970, 0.5698],
        [0.6392, 0.5795, 0.5397],
        [0.5508, 0.6379, 0.5991]], requires_grad=True)
4-th Loss: 3.0703e-02
tensor([[0.4279, 0.1977, 0.5098],
        [0.5860, 0.5618, 0.5531],
        [0.5840, 0.6739, 0.6659]], requires_grad=True)
5-th Loss: 1.8574e-02
tensor([[0.3550, 0.1982, 0.4632],
        [0.5447, 0.5481, 0.5635],
        [0.6097, 0.7019, 0.7179]], requires_grad=True)
6-th Loss: 1.1236e-02
tensor([[0.2983, 0.1986, 0.4269],
        [0.5125, 0.5374, 0.5716],
        [0.6298, 0.7237, 0.7584]], requires_grad=True)
7-th Loss: 6.7970e-03
tensor([[0.2543, 0.1989, 0.3987],
        [0.4875, 0.5291, 0.5779],
        [0.6454, 0.7407, 0.7899]], requi