## PyTorch Tensor Operations

In [2]:
import torch

## Arithmetic Element-wise Operations

In [3]:
a = torch.FloatTensor([[1, 2],
                      [3, 4]])
b = torch.FloatTensor([[2, 2],
                      [3, 3]])

In [4]:
a + b

tensor([[3., 4.],
        [6., 7.]])

In [5]:
a - b

tensor([[-1.,  0.],
        [ 0.,  1.]])

In [6]:
a * b # element wise로 계산됨

tensor([[ 2.,  4.],
        [ 9., 12.]])

In [7]:
a / b

tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])

In [8]:
a == b

tensor([[False,  True],
        [ True, False]])

In [9]:
a != b

tensor([[ True, False],
        [False,  True]])

In [10]:
a ** b # element wise로 계산됨

tensor([[ 1.,  4.],
        [27., 64.]])

## Inplace Operations

In [11]:
print(a)
print(a.mul(b)) # a*b랑 같은 결과로 elementwise로 계산됨.
print(a)
print(a.mul_(b)) # a자리에다가 multiplication 값이 들어감. 메모리 형성 안하고 결과를 덮어씌움.. 이걸 쓴다고 해서 더 속도가 빨라지지는 않지만 메모리할당을 더 하고싶지 않을때 쓰면 좋다.
print(a)

tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])


## Sum, Mean (Dimension Reducing Operations)

In [14]:
x = torch.FloatTensor([[1, 2],
                      [3, 4]])

In [15]:
print(x.sum())
print(x.mean())

tensor(10.)
tensor(2.5000)


In [16]:
print(x.sum(dim = 0))
print(x.sum(dim = -1))

tensor([4., 6.])
tensor([3., 7.])


## Broadcast in Operations

What we did before.

In [12]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[4, 8]])

print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([1, 2])


In [13]:
z = x + y
print(z)
print(z.size())

tensor([[ 5., 10.]])
torch.Size([1, 2])


Broadcast feature provides operations between different shape of tensors.

## Tensor + Scalar

In [17]:
x = torch.FloatTensor([[1, 2],
                      [3, 4]])
y = 1

print(x.size())

torch.Size([2, 2])


In [18]:
z = x + y
print(z)
print(z.size())

tensor([[2., 3.],
        [4., 5.]])
torch.Size([2, 2])


## Tensor + Vector

In [19]:
x = torch.FloatTensor([[1, 2],
                      [4, 8]])
y = torch.FloatTensor([3,
                      5])
print(x.size())
print(y.size()) # (1, 2)랑 같은거

torch.Size([2, 2])
torch.Size([2])


In [20]:
z = x + y
print(z)
print(z.size())

tensor([[ 4.,  7.],
        [ 7., 13.]])
torch.Size([2, 2])


In [21]:
x = torch.FloatTensor([[[1, 2]]])
y = torch.FloatTensor([3, 
                      5])
print(x.size())
print(y.size())

torch.Size([1, 1, 2])
torch.Size([2])


In [22]:
z = x + y
print(z)
print(z.size())

tensor([[[4., 7.]]])
torch.Size([1, 1, 2])


## Tensor + Tensor

In [23]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[3],
                      [5]])
print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([2, 1])


In [24]:
z = x + y
print(z)
print(z.size())

tensor([[4., 5.],
        [6., 7.]])
torch.Size([2, 2])


Note that you need to be careful before using broadcast feature.

broadcast를 통해 쉽게 모양이 다른 tensor들의 연산이 가능할수 있다. 
그러나 잘못된 연산이 나올 수 있기 때문에 강사님은 그냥 일부로 expand해서 쓰는편

## Failure Case

In [25]:
x = torch.FloatTensor([[[1, 2],
                       [4, 8]]])
y = torch.FloatTensor([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
print(x.size())
print(y.size())

z = x + y
print(z)
print(z.size())

torch.Size([1, 2, 2])
torch.Size([3, 3])


RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

broadcast가 불가능한 case도 잇음