## PyTorch Tensor

In [1]:
import torch

## Tensor Allocation

In [2]:
ft = torch.FloatTensor([[1, 2],
                       [3, 4]])
# 2차원 텐서 또는 매트릭스

In [3]:
ft

tensor([[1., 2.],
        [3., 4.]])

In [4]:
lt = torch.LongTensor([[1, 2],
                      [3, 4]])
lt

tensor([[1, 2],
        [3, 4]])

In [5]:
bt = torch.ByteTensor([[1, 0],
                      [0, 1]])

In [7]:
bt

tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)

In [8]:
x = torch.FloatTensor(3, 2) # 선언해주지 않아도 garbage 값이 들어간 텐서 생성할 수 있음.
x

tensor([[4.2882e-08, 4.0372e-08],
        [8.4108e+20, 1.7000e+22],
        [4.1660e-11, 7.1450e+31]])

## NumPy Compatibility

PyTorch의 장점은 NumPy와 호환이 잘됨.

In [9]:
import numpy as np

In [10]:
# Define numpy array
x = np.array([[1, 2],
             [3, 4]])
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [11]:
x = torch.from_numpy(x)
print(x, type(x))

tensor([[1, 2],
        [3, 4]], dtype=torch.int32) <class 'torch.Tensor'>


In [12]:
x = x.numpy()
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


## Tensor Type-casting

In [13]:
ft.long() # float tensor는 float끼리 연산해야함. ft을 long으로 변환

tensor([[1, 2],
        [3, 4]])

In [16]:
lt.float() # long tensor는 long끼리 연산해야함. long을 ft으로 변환

tensor([[1., 2.],
        [3., 4.]])

In [15]:
torch.FloatTensor([1, 0]).byte()

tensor([1, 0], dtype=torch.uint8)

## Get Shape

In [20]:
x = torch.FloatTensor([[[1, 2],
                       [3, 4]],
                      [[5, 6],
                      [7, 8]],
                      [[9, 10],
                      [11, 12]]])

Get tensor type

In [21]:
print(x.size())
print(x.shape)

torch.Size([3, 2, 2])


Get number of dimensions in the tensor

In [23]:
print(x.dim())
print(len(x.size()))

3
3


Get number of elements in certain dimension of the tensor

In [26]:
print(x.size(1))
print(x.shape[1])

2
2


Get number of elements in the last dimension

In [27]:
print(x.size(-1))
print(x.shape[-1])

2
2
