## PyTorch AutoGrad

In [1]:
import torch

In [2]:
x = torch.FloatTensor([[1, 2],
                      [3, 4]]).requires_grad_(True)
# requires_grad_: gradient가 필요한지 묻는 argument

In [3]:
x1 = x + 2
x2 = x - 2
x3 = x1 * x2
y = x3.sum()

print(x1)
print(x2)
print(x3)
print(y)

tensor([[3., 4.],
        [5., 6.]], grad_fn=<AddBackward0>)
tensor([[-1.,  0.],
        [ 1.,  2.]], grad_fn=<SubBackward0>)
tensor([[-3.,  0.],
        [ 5., 12.]], grad_fn=<MulBackward0>)
tensor(14., grad_fn=<SumBackward0>)


In [4]:
y.backward()
# y는 scalar여야함.
# scalar가 아닌 경우 backward를 호출하면 에러가남.

$$ x =
\begin{bmatrix}
x_{(1, 1)} & x_{(1, 2)} \\
x_{(2, 1)} & x_{(2, 2)}
\end{bmatrix}$$

$$ x_{1} = x + 2 $$
$$ x_{2} = x - 2 $$

$$ x_{3} = x_{1} \times x_{2} $$
                $$ = (x+2)(x-2) $$
                $$ = x^{2} - 4 $$
$$ y = sum(x_{3}) $$
     $$ = x_{3,(1, 1)} + x_{3,(1, 2)} + x_{3, (2, 1) } + x_{3, (2, 2) } $$
     
$$ x.grad =
\begin{bmatrix}
\frac{\partial y} {\partial x_{(1,1)}} & \frac{\partial y} {\partial x_{(1,2)}} \\
\frac{\partial y} {\partial x_{(2,1)}} & \frac{\partial y} {\partial x_{(2,2)}}
\end{bmatrix}$$

$$ \frac{\partial y} {\partial x} = 2x$$

In [5]:
print(x.grad)

tensor([[2., 4.],
        [6., 8.]])


In [7]:
print(x)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
