## PyTorch Useful Methods

In [1]:
import torch

### expand : copy the given tensor and concat those at desired dimensions

In [4]:
x = torch.FloatTensor([[[1, 2]],
                      [[3, 4]]])
print(x.size())

torch.Size([2, 1, 2])


In [5]:
y = x.expand(*[2, 3, 2]) # 괄호안의 size로 변환해줌.

print(y)
print(y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


### Implement expand with cat.

In [6]:
y = torch.cat([x, x, x], dim = 1)

print(y)
print(y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


## randperm : Random Permutation

In [7]:
x = torch.randperm(10) # 임의의 순열에 대해서 만들어내는것. 0~9까지를 랜덤하게 섞은 것을 보여줌. shuffleing을 할 수 있음.

print(x)
print(x.size())

tensor([9, 3, 5, 6, 8, 7, 1, 0, 4, 2])
torch.Size([10])


## argmax : Return index of maximum values

In [8]:
x = torch.randperm(3**3).reshape(3, 3, -1)
print(x)
print(x.size())

tensor([[[22, 12, 26],
         [ 1, 19, 14],
         [20, 17,  3]],

        [[10, 25,  4],
         [21, 16, 11],
         [ 9, 13,  8]],

        [[ 5,  0, 15],
         [ 2,  7, 18],
         [ 6, 24, 23]]])
torch.Size([3, 3, 3])


In [9]:
y = x.argmax(dim = -1)

print(y)
print(y.size())

tensor([[2, 1, 0],
        [1, 0, 1],
        [2, 2, 1]])
torch.Size([3, 3])


## topk : Return tuple of top-k values and indices

In [10]:
values, indices = torch.topk(x, k = 1, dim = - 1)

print(values.size())
print(indices.size())

torch.Size([3, 3, 1])
torch.Size([3, 3, 1])


Note that topk didn't reduce the dimension, even in k = 1 cases.

In [11]:
print(values.squeeze(-1))
print(indices.squeeze(-1))

tensor([[26, 19, 20],
        [25, 21, 13],
        [15, 18, 24]])
tensor([[2, 1, 0],
        [1, 0, 1],
        [2, 2, 1]])


In [12]:
print(x.argmax(dim = -1) == indices.squeeze(-1))

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


argmax와 topk를 둘다 써도 되는데 topk의 경우 해당차원이 살아있다는점을 잊지 말아야함.

In [15]:
_, indices = torch.topk(x, k = 2, dim = -1) # 3, 3, k가 나오게됨.
print(indices.size())
print(x.argmax(dim = -1) == indices[:, :, 0])

torch.Size([3, 3, 2])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [16]:
print(indices)

tensor([[[2, 0],
         [1, 2],
         [0, 1]],

        [[1, 0],
         [0, 1],
         [1, 0]],

        [[2, 0],
         [2, 1],
         [1, 2]]])


In [17]:
indices[:, :, 0]

tensor([[2, 1, 0],
        [1, 0, 1],
        [2, 2, 1]])

## Sort by using topk

In [14]:
target_dim = -1
values, indices = torch.topk(x,
                            k = x.size(target_dim), # sorting이 일어남.
                            largest = True)
# sort를 구현한것.
print(values)

tensor([[[26, 22, 12],
         [19, 14,  1],
         [20, 17,  3]],

        [[25, 10,  4],
         [21, 16, 11],
         [13,  9,  8]],

        [[15,  5,  0],
         [18,  7,  2],
         [24, 23,  6]]])


## Topk by using sort

In [18]:
k = 1
values, indices = torch.sort(x, dim = -1, descending = True)
values, indices = values[:, :, :k], indices[:, :, :k]

print(values.squeeze(-1))
print(indices.squeeze(-1))

tensor([[26, 19, 20],
        [25, 21, 13],
        [15, 18, 24]])
tensor([[2, 1, 0],
        [1, 0, 1],
        [2, 2, 1]])


## masked_fill : fill the value if element of mask is True

In [19]:
x = torch.FloatTensor([i for i in range(3**2)]).reshape(3, -1)

print(x)
print(x.size())

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
torch.Size([3, 3])


In [20]:
mask = x > 4
print(mask)

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])


In [21]:
y = x.masked_fill(mask, value = -1) # mask가 true도 -1로 채워 !! 
print(y)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])


## Ones and Zeros

In [22]:
print(torch.ones(2, 3))
print(torch.zeros(2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [23]:
x = torch.FloatTensor([[1, 2, 3],
                      [4, 5, 6]])
print(x.size())

torch.Size([2, 3])


In [25]:
print(torch.ones_like(x)) # type도 같고 device도 같고 size도 같음. device가 다른것끼리 연산하면 에러남.
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
